using System.Collections.Generic;

namespace MEESEEKS.Models.Task
{
    /// <summary>
    /// Represents the result of a task execution by a MEESEEKS agent.
    /// Contains detailed information about the task's outcome, including success status,
    /// output, errors, and any additional results produced during execution.
    /// </summary>
    public class AgentResult
    {
        /// <summary>
        /// Indicates whether the task was successfully completed.
        /// True if the task completed without errors, false otherwise.
        /// </summary>
        public bool Success { get; set; }

        /// <summary>
        /// Detailed message describing the task execution outcome.
        /// Provides context about what was accomplished or why the task failed.
        /// </summary>
        public string Message { get; set; } = string.Empty;

        /// <summary>
        /// The output produced by the task execution.
        /// Contains the primary result or output data generated by the task.
        /// </summary>
        public string Output { get; set; } = string.Empty;

        /// <summary>
        /// Collection of errors that occurred during task execution.
        /// Each entry represents a distinct error or failure condition encountered.
        /// </summary>
        public List<string> Errors { get; set; } = new List<string>();

        /// <summary>
        /// Additional results produced by the task.
        /// Key-value pairs of named results that provide supplementary information
        /// or data generated during task execution.
        /// </summary>
        public Dictionary<string, object> Results { get; set; } = new Dictionary<string, object>();
    }
}
